# File: .github/workflows/php-composer-drush.yml

name: Setup PHP, Composer, and Drush

# Trigger on push to main branch or on pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Install PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Specify the PHP version you need
          extensions: mbstring, pdo, xml, ctype, json, curl
          tools: composer

      # Step 3: Install Composer dependencies
      - name: Install Composer Dependencies
        run: composer install

      # Step 4: Install Drush via Composer
      - name: Install Drush
        run: composer require drush/drush

      # Step 5: Verify Drush installation
      - name: Check Drush version
        run: ./vendor/bin/drush --version
